development:
  password: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  theme_id: "xxxxxxxxxxx"
  store: your-brand-store.myshopify.com
  bucket_size: 40
  refill_rate: 2
  concurrency: 2
  timeout: 30s
  ignore_files:
    - .git/*
    - .gitignore
    - .idea
    - _dev/*